"""webhooks and event outbox flag

Revision ID: 12fe915d90c1
Revises: b7769dddf543
Create Date: 2026-10-07 13:13:44.945091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = '12fe915d90c1'
down_revision: Union[str, Sequence[str], None] = 'b7769dddf543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=80), nullable=False),
    sa.Column('enabled_events', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_webhook_endpoints_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoints'))
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('webhook_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('endpoint_id', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='webhookmessagestatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('delivered_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], name=op.f('fk_webhook_messages_endpoint_id_webhook_endpoints')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_webhook_messages_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_messages')),
    sa.UniqueConstraint('endpoint_id', 'event_id', name=op.f('uq_webhook_messages_endpoint_id'))
    )
    with op.batch_alter_table('webhook_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_messages_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_messages_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_webhook_messages_status'), ['status'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('webhooks_enqueued', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_events_webhooks_enqueued'), ['webhooks_enqueued'], unique=False)

    # Events that happened before webhooks existed must not be sent now.
    # Portable boolean (Postgres rejects "= 1" for a boolean column).
    events = sa.table("events", sa.column("webhooks_enqueued", sa.Boolean))
    op.execute(events.update().values(webhooks_enqueued=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_webhooks_enqueued'))
        batch_op.drop_column('webhooks_enqueued')

    with op.batch_alter_table('webhook_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_messages_status'))
        batch_op.drop_index(batch_op.f('ix_webhook_messages_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_webhook_messages_endpoint_id'))

    op.drop_table('webhook_messages')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_merchant_id'))

    op.drop_table('webhook_endpoints')
    # ### end Alembic commands ###
