"""workers, runtime settings, encrypted webhook secrets

Revision ID: 3ee445b5c0d2
Revises: 12fe915d90c1
Create Date: 2026-10-08 10:59:14.784555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base
from traveai.crypto import decrypt, encrypt


# revision identifiers, used by Alembic.
revision: str = '3ee445b5c0d2'
down_revision: Union[str, Sequence[str], None] = '12fe915d90c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_runtime_settings'))
    )
    op.create_table('worker_leases',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('holder', sa.String(length=120), nullable=False),
    sa.Column('expires_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_worker_leases'))
    )
    # Encrypt existing plain-text secrets in place (needs TRAVEAI_SECRET_KEY in production).
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_encrypted', sa.String(length=255), nullable=True))
    _convert_secrets(source="secret", target="secret_encrypted", fn=encrypt)
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.alter_column('secret_encrypted', nullable=False)
        batch_op.drop_column('secret')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret', sa.VARCHAR(length=80), nullable=True))
    _convert_secrets(source="secret_encrypted", target="secret", fn=decrypt)
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.alter_column('secret', nullable=False)
        batch_op.drop_column('secret_encrypted')

    op.drop_table('worker_leases')
    op.drop_table('runtime_settings')
    # ### end Alembic commands ###


def _convert_secrets(*, source: str, target: str, fn) -> None:
    endpoints = sa.table("webhook_endpoints", sa.column("id"), sa.column(source), sa.column(target))
    conn = op.get_bind()
    for row in conn.execute(sa.select(endpoints.c.id, endpoints.c[source])).all():
        conn.execute(
            endpoints.update()
            .where(endpoints.c.id == row[0])
            .values({target: fn(row[1])})
        )
