"""initial schema

Revision ID: 506085fe9555
Revises: 
Create Date: 2026-10-05 15:57:42.825164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = '506085fe9555'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drop_zones',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('yard', 'rooftop_pad', 'hospital_pad', 'locker', 'curbside', name='dropzonekind', native_enum=False, length=32), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drop_zones'))
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('pharmacy', 'hospital', 'lab', 'restaurant', 'grocery', 'other', name='merchantcategory', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('call_sign', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('idle', 'assigned', 'in_flight', 'returning', 'charging', 'maintenance', 'offline', name='vehiclestatus', native_enum=False, length=32), nullable=False),
    sa.Column('max_payload_kg', sa.Float(), nullable=False),
    sa.Column('max_range_km', sa.Float(), nullable=False),
    sa.Column('cruise_speed_mps', sa.Float(), nullable=False),
    sa.Column('temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('drop_method', sa.Enum('winch', 'land', 'parachute', name='dropmethod', native_enum=False, length=32), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('altitude_ft', sa.Float(), nullable=False),
    sa.Column('base_lat', sa.Float(), nullable=False),
    sa.Column('base_lng', sa.Float(), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('call_sign', name=op.f('uq_vehicles_call_sign'))
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_status'), ['status'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_api_keys_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('quotes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Enum('standard', 'express', 'urgent', name='priority', native_enum=False, length=32), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('infeasible_reasons', sa.JSON(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('expires_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.String(length=300), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=False),
    sa.Column('dropoff_lng', sa.Float(), nullable=False),
    sa.Column('dropoff_address', sa.String(length=300), nullable=True),
    sa.Column('payload_category', sa.Enum('food', 'medical', name='payloadcategory', native_enum=False, length=32), nullable=False),
    sa.Column('payload_weight_kg', sa.Float(), nullable=False),
    sa.Column('payload_length_cm', sa.Float(), nullable=False),
    sa.Column('payload_width_cm', sa.Float(), nullable=False),
    sa.Column('payload_height_cm', sa.Float(), nullable=False),
    sa.Column('payload_temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('payload_fragile', sa.Boolean(), nullable=False),
    sa.Column('payload_prescription', sa.Boolean(), nullable=False),
    sa.Column('payload_description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_quotes_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quotes_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('quote_id', sa.String(length=40), nullable=True),
    sa.Column('dropoff_zone_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'assigned', 'picking_up', 'airborne', 'arriving', 'delivered', 'aborted', 'returned_to_base', 'canceled', 'failed', name='deliverystatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('standard', 'express', 'urgent', name='priority', native_enum=False, length=32), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('external_reference', sa.String(length=64), nullable=True),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('recipient_phone', sa.String(length=32), nullable=True),
    sa.Column('recipient_pin_hash', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('delivered_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('delivered_lat', sa.Float(), nullable=True),
    sa.Column('delivered_lng', sa.Float(), nullable=True),
    sa.Column('proof_photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.String(length=300), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=False),
    sa.Column('dropoff_lng', sa.Float(), nullable=False),
    sa.Column('dropoff_address', sa.String(length=300), nullable=True),
    sa.Column('payload_category', sa.Enum('food', 'medical', name='payloadcategory', native_enum=False, length=32), nullable=False),
    sa.Column('payload_weight_kg', sa.Float(), nullable=False),
    sa.Column('payload_length_cm', sa.Float(), nullable=False),
    sa.Column('payload_width_cm', sa.Float(), nullable=False),
    sa.Column('payload_height_cm', sa.Float(), nullable=False),
    sa.Column('payload_temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('payload_fragile', sa.Boolean(), nullable=False),
    sa.Column('payload_prescription', sa.Boolean(), nullable=False),
    sa.Column('payload_description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['dropoff_zone_id'], ['drop_zones.id'], name=op.f('fk_deliveries_dropoff_zone_id_drop_zones')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_deliveries_merchant_id_merchants')),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name=op.f('fk_deliveries_quote_id_quotes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('quote_id', name=op.f('uq_deliveries_quote_id'))
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_status'), ['status'], unique=False)

    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('delivery_id', sa.String(length=40), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_events_delivery_id_deliveries')),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_events_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_events')),
    sa.UniqueConstraint('id', name=op.f('uq_events_id'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('missions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('delivery_id', sa.String(length=40), nullable=False),
    sa.Column('vehicle_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'aborted', name='missionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('cruise_altitude_ft', sa.Integer(), nullable=False),
    sa.Column('planned_distance_m', sa.Float(), nullable=False),
    sa.Column('started_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ended_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('abort_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_missions_delivery_id_deliveries')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_missions_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions'))
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_missions_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_missions_delivery_id'))

    op.drop_table('missions')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_events_delivery_id'))

    op.drop_table('events')
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_status'))
        batch_op.drop_index(batch_op.f('ix_deliveries_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_external_reference'))

    op.drop_table('deliveries')
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quotes_merchant_id'))

    op.drop_table('quotes')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_merchant_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_status'))

    op.drop_table('vehicles')
    op.drop_table('merchants')
    op.drop_table('drop_zones')
    # ### end Alembic commands ###
