"""delivery requirements, eta and pin lockout

Revision ID: 5099622b4828
Revises: 5707a1124118
Create Date: 2026-10-07 12:01:35.364661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = '5099622b4828'
down_revision: Union[str, Sequence[str], None] = '5707a1124118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('estimated_pickup_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('estimated_dropoff_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('pin_failed_attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('recipient_pin_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('recipient_pin_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('pin_failed_attempts')
        batch_op.drop_column('estimated_dropoff_at')
        batch_op.drop_column('estimated_pickup_at')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
