"""quote details and vehicle wind limit

Revision ID: 5707a1124118
Revises: 506085fe9555
Create Date: 2026-10-07 11:44:58.152402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = '5707a1124118'
down_revision: Union[str, Sequence[str], None] = '506085fe9555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('price_breakdown', sa.JSON(), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('cruise_altitude_ft', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requested_pickup_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('estimated_pickup_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('estimated_dropoff_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.JSON(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_wind_mps', sa.Float(), server_default='12.0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('max_wind_mps')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('weather')
        batch_op.drop_column('estimated_dropoff_at')
        batch_op.drop_column('estimated_pickup_at')
        batch_op.drop_column('requested_pickup_at')
        batch_op.drop_column('cruise_altitude_ft')
        batch_op.drop_column('price_breakdown')
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
