"""simulator mission progress and test failures

Revision ID: b7769dddf543
Revises: 5099622b4828
Create Date: 2026-10-07 12:26:42.338785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = 'b7769dddf543'
down_revision: Union[str, Sequence[str], None] = '5099622b4828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_failure', sa.Enum('high_wind', 'low_battery', 'drop_zone_blocked', name='failurekind', native_enum=False, length=32), nullable=True))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_index', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('dropoff_index', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('phase', sa.Enum('positioning', 'loading', 'delivering', 'awaiting_handoff', 'returning', name='missionphase', native_enum=False, length=32), nullable=True))
        batch_op.add_column(sa.Column('next_waypoint_index', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('phase_elapsed_s', sa.Float(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('package_onboard', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('injected_failure', sa.Enum('high_wind', 'low_battery', 'drop_zone_blocked', name='failurekind', native_enum=False, length=32), nullable=True))
        batch_op.add_column(sa.Column('failure_triggered', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('failure_triggered')
        batch_op.drop_column('injected_failure')
        batch_op.drop_column('package_onboard')
        batch_op.drop_column('phase_elapsed_s')
        batch_op.drop_column('next_waypoint_index')
        batch_op.drop_column('phase')
        batch_op.drop_column('dropoff_index')
        batch_op.drop_column('pickup_index')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('test_failure')

    # ### end Alembic commands ###
