"""delivery tracking token

Revision ID: c29247a1e8fc
Revises: 3ee445b5c0d2
Create Date: 2026-10-08 11:21:49.330207

"""
import secrets
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = 'c29247a1e8fc'
down_revision: Union[str, Sequence[str], None] = '3ee445b5c0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_token', sa.String(length=64), nullable=True))

    # Existing deliveries get their own unguessable token.
    deliveries = sa.table("deliveries", sa.column("id"), sa.column("tracking_token"))
    conn = op.get_bind()
    for (delivery_id,) in conn.execute(sa.select(deliveries.c.id)).all():
        conn.execute(
            deliveries.update()
            .where(deliveries.c.id == delivery_id)
            .values(tracking_token=secrets.token_urlsafe(24))
        )

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.alter_column('tracking_token', nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_deliveries_tracking_token'), ['tracking_token'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_deliveries_tracking_token'), type_='unique')
        batch_op.drop_column('tracking_token')

    # ### end Alembic commands ###
