"""merchant portal users and sessions

Revision ID: ebd15f41e904
Revises: c29247a1e8fc
Create Date: 2026-10-08 11:39:12.766104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import traveai.models.base


# revision identifiers, used by Alembic.
revision: str = 'ebd15f41e904'
down_revision: Union[str, Sequence[str], None] = 'c29247a1e8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('last_login_at', traveai.models.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_users_merchant_id_merchants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('portal_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', traveai.models.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portal_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_sessions'))
    )
    with op.batch_alter_table('portal_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portal_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=60), nullable=True))

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('live_enabled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_column('live_enabled')

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('label')

    with op.batch_alter_table('portal_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portal_sessions_user_id'))

    op.drop_table('portal_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_merchant_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
